### ISSUE TITLE
In /images, `imageTimeStamp` is a Date, it should be a DateTime

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [PhenoLibs/JavaLibraryBuilder#1]
Raised by: @ctucker3 

> For the images endpoint, the return type for the imageTimeStamp is string(date) in the docs, but I believe it should be string(date-time). Looks like it is that way in all of the images endpoints.

Note from @BrapiCoordinatorSelby 
This has been manually corrected in the V1.3 documentation. The description of the `imageTimeStamp ` field does specify that it should be "The date and time the image was taken" So this is not an alteration to the intended spec, but a technical bug within the documentation.
This correction needs to be changed manually in the generated Java code to reflect the expected functionality.

**Comment by peterrosario** [comment]
Merged into master branch in c36b3b6a7650244120193ff89aabe61924d0d10d
